# Generated by Django 4.2.7 on 2025-07-14 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42, unique=True)),
                ('role', models.CharField(choices=[('publisher', 'Publisher'), ('advertiser', 'Advertiser')], max_length=20)),
                ('eth_balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('token_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('impressions', models.IntegerField(default=0)),
                ('earnings_eth', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('earnings_tokens', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_eth', models.DecimalField(decimal_places=8, max_digits=20)),
                ('spent_eth', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.video')),
            ],
        ),
    ]
